version: '3.8'

services:
  investmentmanager-app:
    container_name: investmentmanager-app
    image: docker-test-aspnet-6:latest
    ports:
      - "80:80"
    networks:
      - investmentmanager
  
  investmentmanager-postgres:
    container_name: investmentmanager-postgres
    image: postgres:latest
    restart: unless-stopped
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
    logging:
      options:
        max-size: 10m
        max-file: "3"
    ports:
      - "5444:5432"
    networks:
      - investmentmanager
    volumes:
      - investmentmanager-postgres-volume:/var/lib/postgresql/data

volumes:
  investmentmanager-postgres-volume:  
  
networks:
  investmentmanager: 